version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - Rakambda
    schedule:
      interval: cron
      cronjob: 0 6 * * *
      timezone: Europe/Paris
    pull-request-branch-name:
      separator: '-'
      word-separator: '-'
      branch-name-case: lowercase
    groups:
      docker:
        patterns:
          - docker/*
      actions:
        patterns:
          - actions/*
  - package-ecosystem: npm
    directory: /
    assignees:
      - Rakambda
    schedule:
      interval: cron
      cronjob: 0 6 * * *
      timezone: Europe/Paris
    pull-request-branch-name:
      separator: '-'
      word-separator: '-'
      branch-name-case: lowercase
    cooldown:
      default-days: 4
    groups:
      eslint:
        patterns:
          - eslint
          - '@eslint/*'
          - '@stylistic/eslint-plugin-ts'
          - '@typescript-eslint/*'
      octokit:
        patterns:
          - '@octokit/*'
      actions:
        patterns:
          - actions/*
