name: 'Repo Settings Sync'
description: 'Github Action to setup repository settings'
author: 'Rakambda'

branding:
  icon: 'upload-cloud'
  color: 'purple'

inputs:
  github_token:
    description: 'Github token used to access the APIs'
    required: false
  github_app_id:
    description: 'Github App ID to use to access APIs'
    required: false
  github_app_private_key:
    description: 'Github App private key to use to access APIs'
    required: false
  github_app_installation_id:
    description: 'Github App installation ID to use to access APIs'
    required: false
  config_path:
    description: 'Configuration file'
    required: false
    default: '.github/settings-sync.yml'

runs:
  using: 'node20'
  main: 'dist/index.js'
