name: 'Repo Settings Sync'
description: 'Github Action to setup repository settings'
author: 'Rakambda'

branding:
  icon: 'upload-cloud'
  color: 'purple'

inputs:
  github_token:
    description: 'Github token used to access the APIs'
    required: true
  config_path:
    description: 'Configuration file'
    required: false
    default: '.github/settings-sync.yml'

runs:
  using: 'node20'
  main: 'dist/index.js'
