name: Build dist

on:
  workflow_dispatch:

env:
  NODE_VERSION: 24
  PNPM_VERSION: 10

permissions:
  contents: write

jobs:
  build-dist:
    name: Build dist folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5.0.0
      - name: Setup PNPM
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Commit dist folder
        run: |
          git add dist
      - name: Commit report
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Automated dist build"
          git push
          